version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: "npm"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
      day: "friday"
